include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_empty_else: error
    avoid_print: error
    avoid_dynamic_calls: error
    avoid_slow_async_io: error
    discarded_futures: error
    empty_statements: error
    unnecessary_statements: error
    avoid_classes_with_only_static_members: error
    avoid_multiple_declarations_per_line: error
    eol_at_end_of_file: error
    leading_newlines_in_multiline_strings: error
    library_annotations: error
    always_put_control_body_on_new_line: ignore



linter:
  rules:
    - avoid_print
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - avoid_catching_errors
    - avoid_final_parameters
    - avoid_multiple_declarations_per_line
    - combinators_ordering
    - constant_identifier_names
    - empty_catches
    - directives_ordering
    - eol_at_end_of_file
    - leading_newlines_in_multiline_strings
    - library_annotations
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - camel_case_types: true
